jobs:
  - template: ../../azure-pipelines/jobs/run-tests.yml
    parameters:
      serviceName: ci-public-api-php-client
      testCommand: bash -c 'wait-for-it.sh --strict --timeout=120 ci-public-api:8080 && composer ci'
      variables:
        STORAGE_API_URL: $(STORAGE_API_URL__AWS)
      secrets:
        STORAGE_API_TOKEN: $(PUBLIC_API_PHP_CLIENT__STORAGE_API_TOKEN__AWS)
        MANAGE_API_TOKEN: $(INTERNAL_API__MANAGE_TOKEN__AWS)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        LOG_ABS_CONNECTION_STRING: $(LOG_ABS_CONNECTION_STRING)
