version: "3"

services:
  tests: &tests
    image: keboola/dev-job-queue-api-php-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build/logs/:/code/build/logs/
    environment:
      public_queue_api_url:
      test_storage_api_token:
      storage_api_url:
    command: ['composer', 'ci']

  tests73:
    build:
      context: .
      dockerfile: Dockerfile73
    environment:
      public_queue_api_url:
      test_storage_api_token:
      storage_api_url:
    command: ['composer', 'ci']

  tests-local:
    <<: *tests
    volumes:
      - .:/code
